#define FLOW_TAP_TERM 100
#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_TIMEOUT 140
#define SERIAL_NUMBER "v5qdn/404yVM"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 43

#define RGB_MATRIX_STARTUP_SPD 60

